---
name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  DOCKERHUB_URL: leandelivery/docker-systemd
  DOCKERHUB_USERNAME: leandeliveryrobot
jobs:
  centos7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        env:
          TAG: centos7
        run: |
          docker build -t $DOCKERHUB_URL:$TAG -f Dockerfile-$TAG .
          docker image ls
  centos8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        env:
          TAG: centos8
        run: |
          docker build -t $DOCKERHUB_URL:$TAG -f Dockerfile-$TAG .
          docker image ls
  ubuntu-14_04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        env:
          TAG: ubuntu-14.04
        run: |
          docker build -t $DOCKERHUB_URL:$TAG -f Dockerfile-$TAG .
          docker image ls
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $DOCKERHUB_URL:$TAG
          docker logout
  ubuntu-16_04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        env:
          TAG: ubuntu-16.04
        run: |
          docker build -t $DOCKERHUB_URL:$TAG -f Dockerfile-$TAG .
          docker image ls
  ubuntu-18_04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        env:
          TAG: ubuntu-18.04
        run: |
          docker build -t $DOCKERHUB_URL:$TAG -f Dockerfile-$TAG .
          docker image ls
  ubuntu-20_04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        env:
          TAG: ubuntu-20.04
        run: |
          docker build -t $DOCKERHUB_URL:$TAG -f Dockerfile-$TAG .
          docker image ls
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $DOCKERHUB_URL:$TAG
          docker logout
